# Generated by Django 3.0.5 on 2020-05-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderndmisc', '0002_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
